// Generated by build.py!
//
// Contains unique build info (useful for tracking the version people are using!)
namespace NEP.MonoDirector
{
    static partial class BuildInfo
    {
		public const int Epoch = 1713944156;
		public const string GitCommit = "f732c23897b78324e461ece93f47ffc84c8f8d61";
    }
}