// Generated by build.py!
//
// Contains unique build info (useful for tracking the version people are using!)
namespace NEP.MonoDirector
{
    static partial class BuildInfo
    {
		public const int Epoch = 1713922592;
		public const string GitCommit = "55688bbd038d8a21818e27988776394a7410710b";
    }
}