// Generated by build.py!
//
// Contains unique build info (useful for tracking the version people are using!)
namespace NEP.MonoDirector
{
    static partial class BuildInfo
    {
		public const int Epoch = 1715193422;
		public const string GitCommit = "49c701b38662292f49746f0caa12ed928dc9556b";
    }
}